name: Bugfest

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Bug Invasion
      run: |
        echo "${ANDROID_HOME}/build-tools/35.0.0" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'oracle'
    - name: Bug Infestation
      run: |
        chmod +x ./gradlew
        ./gradlew deploy
    - name: Bug Extermination
      uses: actions/upload-artifact@v4
      with:
        name: MinD-Bug
        path: build/libs/${{ github.event.repository.name }}.jar
